# Generated by Django 5.2.4 on 2025-08-02 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_event_banner_remove_user_avatar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='updated_at',
        ),
    ]
